checks:
  php:
    code_rating: true
    duplication: true
    excluded_dependencies:
      - magento/framework
      - magento/module-catalog-inventory


tools:
  external_code_coverage:
    timeout: 600    # Timeout in seconds.
