sudo: false

language: php

matrix:
  include:
    - php: 7.0
      env: deps=low
    - php: 7.0
      env: cover=yes

env:
  global:
    - deps=no
    - cover=no

install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - if [ "$deps" = "no" ]; then composer $flag install; fi;
  - if [ "$deps" = "low" ]; then composer $flag --prefer-lowest --prefer-stable update; fi;

script:
  - mkdir -p build/logs
  - if [ "$cover" = "no" ]; then ./vendor/bin/phpunit; fi;
  - if [ "$cover" = "yes" ]; then ./vendor/bin/phpunit --coverage-clover build/logs/coverage.xml; fi;

before_install:
  - composer self-update
  - composer config --quiet github-oauth.github.com $GITHUB_TOKEN
  - if [[ ! $GITHUB_TOKEN ]]; then echo "no github token"; fi
  - if [[ ! $GITHUB_TOKEN ]]; then flag=--prefer-source; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.xml
