# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
image: meanbee/magento2-php:7.0-cli

pipelines:
  default:
    - step:
        script:
          - docker-environment
          - composer install -n
          - vendor/bin/grumphp run
