
# Installation


## Requirements

* Installed and configured Magento 2.
* The Magento cron set up and running ([official how to](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html)).
* A Stockbase username and password with suppliers connected to your account.


## Download the module


### Using Composer {#composer-installation}

This is the recommended way of installing the module for Magento 2.
It allows to automatically download the module and all its dependencies using just a single console command.

1. Make sure you have [Composer](https://getcomposer.org/) installed on your system.
2. Navigate to your Magento 2 installation directory (where the `composer.json` and `composer.lock` files are located).
3. Execute the command: `composer require stockbase/magento2-integration`


### Manual installation

**Warning!** This installation method recommended only for development and we assume that you know how to work with PHP and Composer.
If you're not sure if you need this time of installation, please follow instructions for the [Composer installation](#composer-installation) above.

1. Download the zip archive with the extension.
2. Extract it into the `<magento root folder>/app/code/Stockbase/Integration` directory inside your Magento installation.
3. Install all required dependencies from the extension's `composer.json` file into your main magento project.
   For example: `composer require dividebv/phpdivideiq:^0.5.0 beberlei/assert:^2.4`.
   See the `require` section in the module's `composer.json` file.



## Run the installation procedure

Execute the following commands in the Magento installation directory:  
```
php bin/magento module:enable Stockbase_Integration
php bin/magento setup:upgrade
``` 

After successful installation, you can continue by [configuring](#configuration) the module in the admin panel.


